### ISSUE TITLE
KeyError for Chart Data in Dashboard

### ISSUE THREAD

**Issue by k----n** [milesmcc/shynet#164]
Recently updated shynet to use the latest dockerhub image and came across this:
```
ERROR Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/usr/src/shynet/dashboard/views.py", line 39, in get_context_data
    service.stats = service.get_core_stats(
  File "/usr/src/shynet/core/models.py", line 117, in get_core_stats
    comparison_data = self.get_relative_stats(
  File "/usr/src/shynet/core/models.py", line 203, in get_relative_stats
    chart_data, chart_tooltip_format, chart_granularity = self._get_chart_data(
  File "/usr/src/shynet/core/models.py", line 295, in _get_chart_data
    chart_data[k["date"]]["hits"] = k["count"]
KeyError: datetime.date(2021, 6, 1)
```

**Comment by milesmcc** [comment]
Sorry about this. It's a known issue and will be fixed in the next release. The issue occurs when a session starts late at night and extends into the next day, but no other sessions exist on that day. I'll publish a new release shortly.

**Comment by milesmcc** [comment]
Is this resolved? Just released a new version.

**Comment by k----n** [comment]
Thanks for looking into this so quickly!

It seems to be fixed when I restart the container without rebuilding it?

I also rebuilt the container from the source repo, so hopefully it's fixed.

I'll reopen this issue if it comes up again.

**Comment by tusharsadhwani** [comment]
Hey @milesmcc I'm facing the same issue again, using the latest version.

**Comment by tusharsadhwani** [comment]
```
shynet_main  | ERROR Internal Server Error: /dashboard/
shynet_main  | Traceback (most recent call last):
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
shynet_main  |     response = get_response(request)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
shynet_main  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
shynet_main  |     return self.dispatch(request, *args, **kwargs)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
shynet_main  |     return super().dispatch(request, *args, **kwargs)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
shynet_main  |     return handler(request, *args, **kwargs)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/list.py", line 157, in get
shynet_main  |     context = self.get_context_data()
shynet_main  |   File "/usr/src/shynet/dashboard/views.py", line 39, in get_context_data
shynet_main  |     service.stats = service.get_core_stats(
shynet_main  |   File "/usr/src/shynet/core/models.py", line 116, in get_core_stats
shynet_main  |     main_data = self.get_relative_stats(start_time, end_time)
shynet_main  |   File "/usr/src/shynet/core/models.py", line 203, in get_relative_stats
shynet_main  |     chart_data, chart_tooltip_format, chart_granularity = self._get_chart_data(
shynet_main  |   File "/usr/src/shynet/core/models.py", line 295, in _get_chart_data
shynet_main  |     chart_data[k["date"]]["hits"] = k["count"]
shynet_main  | KeyError: datetime.date(2021, 9, 12)
```

**Comment by tusharsadhwani** [comment]
killing/restarting docker-compose doesn't fix it for me.

**Comment by haaavk** [comment]
It looks like old code. 
There is an if statement in line 295 in "/usr/src/shynet/core/models.py" in latest code.
https://github.com/milesmcc/shynet/blob/03ced00f631281163d2a907656fba1e8729040cb/shynet/core/models.py#L295
Maybe there is something wrong with docker image?

**Comment by milesmcc** [comment]
Yeah I believe the issue here is that I haven't officially made a new release for v0.11 yet. I'll do that this weekend. In the meantime, the milesmcc/shynet:edge tag should have the fix.
