### ISSUE TITLE
500 Error - Possible corrupted data on day changes

### ISSUE THREAD

**Issue by sergioisidoro** [milesmcc/shynet#174]
Getting the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/usr/src/shynet/dashboard/views.py", line 39, in get_context_data
    service.stats = service.get_core_stats(
  File "/usr/src/shynet/core/models.py", line 116, in get_core_stats
    main_data = self.get_relative_stats(start_time, end_time)
  File "/usr/src/shynet/core/models.py", line 203, in get_relative_stats
    chart_data, chart_tooltip_format, chart_granularity = self._get_chart_data(
  File "/usr/src/shynet/core/models.py", line 295, in _get_chart_data
    chart_data[k["date"]]["hits"] = k["count"]
KeyError: datetime.date(2021, 9, 30)
```

I got a Session at `Sept. 30, 2021, 12:02 a.m.` So I'm wondering if there's some race condition / or incoherent timestamp on the turn of the day, because as soon as I deleted the record, the dashboard started working again.

**Comment by haaavk** [comment]
Thanks for bug report. It's known issue from old version.
Look at #158 #164 and #170 for more info.
