### ISSUE TITLE
Incorrect calculation of month value

### ISSUE THREAD

**Issue by wolfpld** [milesmcc/shynet#185]
```
shynet_main  | [2022-01-01 00:04:18 +0000] [9] [INFO] Booting worker with pid: 9
shynet_main  | ERROR Internal Server Error: /dashboard/
shynet_main  | Traceback (most recent call last):
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
shynet_main  |     response = get_response(request)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
shynet_main  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
shynet_main  |     return self.dispatch(request, *args, **kwargs)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
shynet_main  |     return super().dispatch(request, *args, **kwargs)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
shynet_main  |     return handler(request, *args, **kwargs)
shynet_main  |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/list.py", line 157, in get
shynet_main  |     context = self.get_context_data()
shynet_main  |   File "/usr/src/shynet/dashboard/views.py", line 36, in get_context_data
shynet_main  |     data = super().get_context_data(**kwargs)
shynet_main  |   File "/usr/src/shynet/dashboard/mixins.py", line 64, in get_context_data
shynet_main  |     data["date_ranges"] = self.get_date_ranges()
shynet_main  |   File "/usr/src/shynet/dashboard/mixins.py", line 50, in get_date_ranges
shynet_main  |     "start": now.replace(day=1, month=now.month - 1),
shynet_main  | ValueError: month must be in 1..12
```

```
REPOSITORY                TAG           IMAGE ID       CREATED
milesmcc/shynet           latest        8fc7868f03dd   3 months ago
```

**Comment by fightforlife** [comment]
Exactly the same error here starting on years change.

**Comment by milesmcc** [comment]
Hmm. Seeing it myself as well. TIL that January 2022 is actually month 13 of 2021.

**Comment by milesmcc** [comment]
Fixed in https://github.com/milesmcc/shynet/commit/4b4c8f207e94ac1b692d75e0ee826c55fbe23a14. Will release shortly — in the meantime, the fixed build should be up on `:latest` in a few minutes.

**Comment by milesmcc** [comment]
Fixed in v0.12.0, released just now. Happy new year!

**Comment by haaavk** [comment]
It could be fixed by:
```python
            {
                "name": "Last month",
                "start": (now.replace(day=1) - timezone.timedelta(days=1)).replace(
                    day=1
                ),
                "end": now.replace(day=1) - timezone.timedelta(days=1),
            },

```

**Comment by milesmcc** [comment]
Yep, that also makes sense. Would accept that PR.
