### ISSUE TITLE
v0.12.0 bug ?

### ISSUE THREAD

**Issue by christophemacabiau** [milesmcc/shynet#193]
I upgraded to v12 last week because of #191
I discover today that the hits are not saved anymore : I get in the browser
```
script.js:32 POST https://shynet:8080/ingress/XXXscript.js net::ERR_NAME_NOT_RESOLVED
```
obviously the host is incorrect (it's the docker host)

In the shynet logs, I also have this error:
```
[ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write_file(respiter)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 385, in write_file
    if not self.sendfile(respiter):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 375, in sendfile
    self.sock.sendfile(respiter.filelike, count=nbytes)
  File "/usr/local/lib/python3.10/socket.py", line 484, in sendfile
    return self._sendfile_use_sendfile(file, offset, count)
  File "/usr/local/lib/python3.10/socket.py", line 348, in _sendfile_use_sendfile
    self._check_sendfile_params(file, offset, count)
  File "/usr/local/lib/python3.10/socket.py", line 462, in _check_sendfile_params
    raise ValueError(
ValueError: count must be a positive integer (got 0)
```

Do I have something to change in the shynet configuration?

**Comment by christophemacabiau** [comment]
ok for the second error, it's  #189

**Comment by CasperVerswijvelt** [comment]
If you are using a reverse proxy in front of your shynet instance, does it correctly pass through the host header?

In nginx this would be `proxy_set_header Host $http_host;`

**Comment by christophemacabiau** [comment]
Thanks @CasperVerswijvelt 
You are right, we need to set the header in the nginx config. Maybe I am wrong but it seems that it's something new? It was working before, and without the header?
It's working now! Thanks.
