### ISSUE TITLE
Docker-less troubles

### ISSUE THREAD

**Issue by CarlSinclair** [milesmcc/shynet#329]
As discussed in #9, I've been trying to get shynet up and running without docker in order to submit a PR with documentation. I'm using RHEL but once done the instructions can easily be translated into Debian or any other Linux flavor.

I'm running into issues. Here's what I've done so far:

```sudo dnf install -y python3 python3-pip git gcc```
```curl -sSL https://install.python-poetry.org | python3 -```
```git clone https://github.com/milesmcc/shynet.git```
```cd shynet```
```source venv/bin/activate```
```poetry install```
set up the .env file
set up a corresponding Caddy site block
```poetry run python manage.py migrate```
```poetry run python manage.py collectstatic```

Here's the output:
```File "shynet/shynet/manage.py", line 21, in <module>
    main()
  File "shynet/shynet/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/root/.cache/pypoetry/virtualenvs/shynet-p4mndYDs-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.cache/pypoetry/virtualenvs/shynet-p4mndYDs-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/root/.cache/pypoetry/virtualenvs/shynet-p4mndYDs-py3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.cache/pypoetry/virtualenvs/shynet-p4mndYDs-py3.9/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/root/.cache/pypoetry/virtualenvs/shynet-p4mndYDs-py3.9/lib/python3.9/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'allauth'
```

``` - Installing django-allauth (0.45.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "/root/.local/share/pypoetry/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/root/.local/share/pypoetry/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
    File "/root/.local/share/pypoetry/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 134, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/tmpam4wz8v1/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
    File "/tmp/tmpam4wz8v1/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
      self.run_setup()
    File "/tmp/tmpam4wz8v1/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 497, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/tmp/tmpam4wz8v1/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 9, in <module>
  ImportError: cannot import name 'convert_path' from 'setuptools' (/tmp/tmpam4wz8v1/.venv/lib/python3.9/site-packages/setuptools/__init__.py)


  at ~/.local/share/pypoetry/venv/lib64/python3.9/site-packages/poetry/installation/chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with django-allauth (0.45.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "django-allauth (==0.45.0)"'.```

I was able to install django-allauth manually using pip, but that doesn't prevent poetry from trying to install it. I couldn't find a ```requirements.py``` file to remove it as a dependency.

**Comment by milesmcc** [comment]
Dependencies are defined in the `pyproject.toml` file; perhaps remove (or modify) `django-allauth` there? And feel free to do a dependency bump (if everything works smoothly after that bump, please also feel free to upstream it as a PR).

Docker is the only officially supported way of running Shynet—too much surface area for me to maintain otherwise—so I'm going to close this issue, though perhaps others can chime in if they have ideas for how to resolve this issue.

**Comment by CarlSinclair** [comment]
I got the server running and successfully logged in, but I'm getting a weird error:

```
Forbidden (403)
CSRF verification failed. Request aborted.
```

Even though the exact domain is in the .env file. I even replaced it with https:// to allow all domains, and the error persists. Is there another setting somewhere for trusted origins?

**Comment by CarlSinclair** [comment]
For anyone who finds this and would like to help, I figured out the django allauth issue from this [commit](https://github.com/milesmcc/shynet/commit/0eb37141499515eef4fe787bfced53d02b1b4c8f) that addresses exactly that. 

The command in question is ```poetry run pip install "Cython<3.0" "pyyaml==5.4.1" "django-allauth==0.45.0" --no-build-isolation``` followed by ```poetry install```
