### ISSUE TITLE
IP version mismatch when processing ignored IPs

### ISSUE THREAD

**Issue by mrspartak** [milesmcc/shynet#57]
As I can guess this is something with IP version mismatch?
```
ozq4l  2a02:2168:8abf:ad00:e85d:2f13:b1f:c00/128 and 192.168.1.1/32 are not of the same version
ozq4l  Traceback (most recent call last):
ozq4l    File "/usr/src/shynet/analytics/tasks.py", line 67, in ingress_request
ozq4l      if ignored_network.supernet_of(remote_ip):
ozq4l    File "/usr/local/lib/python3.8/ipaddress.py", line 1004, in supernet_of
ozq4l      return self._is_subnet_of(other, self)
ozq4l    File "/usr/local/lib/python3.8/ipaddress.py", line 991, in _is_subnet_of
ozq4l      raise TypeError(f"{a} and {b} are not of the same version")
ozq4l  TypeError: 2a02:2168:8abf:ad00:e85d:2f13:b1f:c00/128 and 192.168.1.1/32 are not of the same version
ozq4l  2a02:2168:8abf:ad00:e85d:2f13:b1f:c00/128 and 192.168.1.1/32 are not of the same version
ozq4l  Traceback (most recent call last):
ozq4l    File "/usr/src/shynet/analytics/tasks.py", line 67, in ingress_request
ozq4l      if ignored_network.supernet_of(remote_ip):
ozq4l    File "/usr/local/lib/python3.8/ipaddress.py", line 1004, in supernet_of
ozq4l      return self._is_subnet_of(other, self)
ozq4l    File "/usr/local/lib/python3.8/ipaddress.py", line 991, in _is_subnet_of
ozq4l      raise TypeError(f"{a} and {b} are not of the same version")
ozq4l  TypeError: 2a02:2168:8abf:ad00:e85d:2f13:b1f:c00/128 and 192.168.1.1/32 are not of the same version
ozq4l  2a02:2168:8abf:ad00:e85d:2f13:b1f:c00/128 and 192.168.1.1/32 are not of the same version
ozq4l  Traceback (most recent call last):
ozq4l    File "/usr/src/shynet/analytics/tasks.py", line 67, in ingress_request
ozq4l      if ignored_network.supernet_of(remote_ip):
ozq4l    File "/usr/local/lib/python3.8/ipaddress.py", line 1004, in supernet_of
ozq4l      return self._is_subnet_of(other, self)
ozq4l    File "/usr/local/lib/python3.8/ipaddress.py", line 991, in _is_subnet_of
ozq4l      raise TypeError(f"{a} and {b} are not of the same version")
ozq4l  TypeError: 2a02:2168:8abf:ad00:e85d:2f13:b1f:c00/128 and 192.168.1.1/32 are not of the same version
ozq4l  2a02:2168:8abf:ad00:e85d:2f13:b1f:c00/128 and 192.168.1.1/32 are not of the same version
ozq4l  Traceback (most recent call last):
ozq4l    File "/usr/src/shynet/analytics/tasks.py", line 67, in ingress_request
ozq4l      if ignored_network.supernet_of(remote_ip):
ozq4l    File "/usr/local/lib/python3.8/ipaddress.py", line 1004, in supernet_of
ozq4l      return self._is_subnet_of(other, self)
ozq4l    File "/usr/local/lib/python3.8/ipaddress.py", line 991, in _is_subnet_of
ozq4l      raise TypeError(f"{a} and {b} are not of the same version")
ozq4l  TypeError: 2a02:2168:8abf:ad00:e85d:2f13:b1f:c00/128 and 192.168.1.1/32 are not of the same version
```

**Comment by milesmcc** [comment]
Ah, interesting. Good edge case. What's happening is that Shynet is trying to check if an IP is in the ignore list, but can't because the ignore list is ipv4 and the ip is ipv6.

Leaving this open for now, will fix sometime this weekend. In the meantime, a temporary fix is to clear the ignore list.

**Comment by mrspartak** [comment]
Ok, thanks
