### ISSUE TITLE
Session details gives error 500 when user is not superuser

### ISSUE THREAD

**Issue by seriousm4x** [milesmcc/shynet#74]
I've created a second account for someone else, set him as a collaborator for the service and granted him every right possible (including "analytics | session | Can view session") in the user settings. Still, when he clicks on a specific user session, he gets an error 500 from the server.

When I give him superuser status he can view session details.

Not sure if it's a bug but a user shouldn't need superuser rights to view session details.

(I added an image where it's not working but the user has all rights)
![2020-08-18 11_58_28](https://user-images.githubusercontent.com/23456686/90500568-5c909f00-e14b-11ea-9ecc-02ae9067738d.png)

**Comment by milesmcc** [comment]
Hmm, this is strange; I will try to replicate. In the mean time, are there any errors printed to the logs?

**Comment by seriousm4x** [comment]
Yes sure, don't know why I forgot. I replaced the service and session IDs.
```
shynet_1  | ERROR Internal Server Error: /dashboard/service/xyz/sessions/xyz/
shynet_1  | Traceback (most recent call last):
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
shynet_1  |     response = get_response(request)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
shynet_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 73, in view
shynet_1  |     return self.dispatch(request, *args, **kwargs)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
shynet_1  |     return super().dispatch(request, *args, **kwargs)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 83, in dispatch
shynet_1  |     if not self.has_permission():
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/rules/contrib/views.py", line 50, in has_permission
shynet_1  |     return self.request.user.has_perms(perms, obj)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 301, in has_perms
shynet_1  |     return all(self.has_perm(perm, obj) for perm in perm_list)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 301, in <genexpr>
shynet_1  |     return all(self.has_perm(perm, obj) for perm in perm_list)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 294, in has_perm
shynet_1  |     return _user_has_perm(self, perm, obj)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 204, in _user_has_perm
shynet_1  |     if backend.has_perm(user, perm, obj):
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/rules/permissions.py", line 32, in has_perm
shynet_1  |     return has_perm(perm, user, *args, **kwargs)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/rules/permissions.py", line 24, in has_perm
shynet_1  |     return permissions.test_rule(name, *args, **kwargs)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/rules/rulesets.py", line 6, in test_rule
shynet_1  |     return name in self and self[name].test(*args, **kwargs)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/rules/predicates.py", line 154, in test
shynet_1  |     return bool(self._apply(*args))
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/rules/predicates.py", line 213, in _apply
shynet_1  |     result = self.fn(*callargs)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/rules/predicates.py", line 165, in OR
shynet_1  |     return self._combine(other, operator.or_, args)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/rules/predicates.py", line 184, in _combine
shynet_1  |     self_result = self._apply(*args)
shynet_1  |   File "/usr/local/lib/python3.8/site-packages/rules/predicates.py", line 213, in _apply
shynet_1  |     result = self.fn(*callargs)
shynet_1  |   File "/usr/src/shynet/core/rules.py", line 14, in is_service_owner
shynet_1  |     return service.owner == user
shynet_1  | AttributeError: 'Session' object has no attribute 'owner'
```

**Comment by milesmcc** [comment]
Fixed in v0.6.3. Thanks!

**Comment by seriousm4x** [comment]
Well that was quick. Thanks! I will test it, once the update is on docker.

**Comment by seriousm4x** [comment]
works!
