### ISSUE TITLE
File type mismatch on the script.js

### ISSUE THREAD

**Issue by breadbored** [milesmcc/shynet#8]
Not exactly sure when this started happening, but when trying to load the script on my webpage, Firefox gives me the following error:

`The resource from “https://<my-domain>/ingress/<site-id>/script.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

This is due to my script.js giving a 500 Error with the following traceback:

```
ERROR Internal Server Error: /ingress/<site-id>/script.js
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 552, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 578, in _connect
    for res in socket.getaddrinfo(self.host, self.port, self.socket_type,
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/src/shynet/analytics/views/ingress.py", line 64, in dispatch
    origins = cache.get(f"service_origins_{service_uuid}")
  File "/usr/local/lib/python3.8/site-packages/redis_cache/backends/base.py", line 30, in wrapped
    return method(self, client, key, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis_cache/backends/base.py", line 267, in get
    return self._get(client, key, default)
  File "/usr/local/lib/python3.8/site-packages/redis_cache/backends/base.py", line 255, in _get
    value = client.get(key)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1579, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis.default.svc.cluster.local:6379. Name or service not known.
```

This is the case for both the code I pulled yesterday and the code I just pulled before writing this.

**Comment by milesmcc** [comment]
Are you running Shynet using the default settings? Unless you have an external Redis server setup, I’d try running Shynet without the env settings that specify `cluster.local` values.

**Comment by breadbored** [comment]
That was exactly the problem. I was using an old `.env` file and the redis settings were still set.
