### ISSUE TITLE
ZeroDivisionError in render function

### ISSUE THREAD

**Issue by soneji** [milesmcc/shynet#89]
Hi

I am having an issue with shynet for only one of my accounts. Is there any way to fix this or put it into a try/except? Maybe have a value this expression defaults to if there is an error?

Thank you

```
shynet_1  | ERROR Internal Server Error: /dashboard/
shynet_1  | Traceback (most recent call last):
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
shynet_1  |     response = get_response(request)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 202, in _get_response
shynet_1  |     response = response.render()
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
shynet_1  |     self.content = self.rendered_content
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
shynet_1  |     return template.render(context, self._request)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
shynet_1  |     return self.template.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
shynet_1  |     return self._render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
shynet_1  |     return self.nodelist.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
shynet_1  |     bit = node.render_annotated(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
shynet_1  |     return self.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
shynet_1  |     return compiled_parent._render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
shynet_1  |     return self.nodelist.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
shynet_1  |     bit = node.render_annotated(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
shynet_1  |     return self.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
shynet_1  |     result = block.nodelist.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
shynet_1  |     bit = node.render_annotated(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
shynet_1  |     return self.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
shynet_1  |     result = block.nodelist.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
shynet_1  |     bit = node.render_annotated(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
shynet_1  |     return self.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 211, in render
shynet_1  |     nodelist.append(node.render_annotated(context))
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
shynet_1  |     return self.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 192, in render
shynet_1  |     return template.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 172, in render
shynet_1  |     return self._render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
shynet_1  |     return self.nodelist.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
shynet_1  |     bit = node.render_annotated(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
shynet_1  |     return self.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 516, in render
shynet_1  |     return self.nodelist.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
shynet_1  |     bit = node.render_annotated(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
shynet_1  |     return self.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/library.py", line 234, in render
shynet_1  |     return t.render(new_context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 172, in render
shynet_1  |     return self._render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
shynet_1  |     return self.nodelist.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
shynet_1  |     bit = node.render_annotated(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
shynet_1  |     return self.render(context)
shynet_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/library.py", line 192, in render
shynet_1  |     output = self.func(*resolved_args, **resolved_kwargs)
shynet_1  |   File "/usr/src/shynet/dashboard/templatetags/helpers.py", line 76, in percent_change_display
shynet_1  |     change = int(round(100 * abs(end - start) / start))
shynet_1  | ZeroDivisionError: division by zero
```

**Comment by milesmcc** [comment]
Thanks! Fixed in v0.7.2. It will be published to Docker Hub shortly. Let me know if you run into any issues.

**Comment by soneji** [comment]
Hi @milesmcc 

Your fix appears to not have actually fixed my error. Maybe a try/except would work better?

I am now getting:

```
shynet_1  |   File "/usr/src/shynet/dashboard/templatetags/helpers.py", line 76, in percent_change_display
shynet_1  |     change = int(round(100 * abs(end - start) / max(start, 1)))
shynet_1  | TypeError: '>' not supported between instances of 'int' and 'datetime.timedelta'
```

**Comment by milesmcc** [comment]
A try/except could work, except I'd rather solve the root issue. In this case, I think a try/catch would only mask other issues (and would be bad style). Datetimes shouldn't be running through `percent_change_display`. I'll dig a bit further.

**Comment by milesmcc** [comment]
I'm having trouble replicating this error. I see from your original error report that this is happening on `/dashboard`. Could you provide me with more information about what is going on? For example, starting with a completely empty Shynet instance, what do you need to do to see this error?

**Comment by soneji** [comment]
I am also very confused about why this error is occuring, but I have setup a shynet instance around August 2020 and the error just manifested itself. I think it may be an issue with the some database data, but it has obviously occured by itself over time. Additionally, the error only occurs for one of the users in my shynet instance, making me think it is related to one of their sites. 

Can this issue be re-opened?

**Comment by soneji** [comment]
I am happy to run modifications to my local shynet repo, with the existing database, to help debug the issue. 

I will change my `docker-compose` file to `build: .` instead of `image:`

**Comment by zmiguel** [comment]
Same issue here, running on docker

**Comment by milesmcc** [comment]
@zmiguel and @soneji -- could either of you let me know the steps you need to take to see this issue? When does it happen? Is it for the primary admin user? Is it for non-admin users? Reproduction steps would be very helpful! Thanks.

**Comment by milesmcc** [comment]
For now, I've just added a try/catch as @soneji mentioned. I'd like to change this in the future once I isolate the issue, but it should fix things for now.

**Comment by soneji** [comment]
Thank you @milesmcc 
This has fixed the issue for me. 
I would still be happy to help you debug the problem in the future

**Comment by zmiguel** [comment]
@milesmcc I'm not sure what caused it, I have 3 sites running that I had set up a few weeks ago, and yesterday the dashboard just stopped working for me.
I only have one user so yes this happens on the primary admin user.

Your last change did fix it.

**Comment by milesmcc** [comment]
Got it. @zmiguel -- would you mind sending a (redacted, if necessary) photo of the dashboard? Thanks! Specifically, I'm curious if any of the net change indicators have `?` in them.

**Comment by zmiguel** [comment]
@milesmcc you mean like that on the first one?

<details>
<summary>Screenshot</summary>

![7351f4a5-4423-480a-b328-05d7f44d1fb4](https://user-images.githubusercontent.com/4400540/104219524-26bfc000-5436-11eb-9f2b-112a04badcc2.png)

</details>

**Comment by milesmcc** [comment]
Cool, got it. I'm going to reopen this issue now so that it stays on my mind to fix!
